import tkinter as tk


class StrategyMonitor(tk.Frame):

    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent)
        self.controller = controller

        # UI elements from Figma
        # This file was generated by the Tkinter Designer by Parth Jadhav
        # https://github.com/ParthJadhav/Tkinter-Designer

        from pathlib import Path

        # from tkinter import *
        # Explicit imports to satisfy Flake8
        from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"./frame2")

        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        # window = Tk()
        #
        # window.geometry("1096x728")
        # window.configure(bg="#F1F5F9")

        canvas = Canvas(
            self,
            bg="#F1F5F9",
            height=728,
            width=1096,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            548.0,
            364.0,
            image=image_image_1
        )

        image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = canvas.create_image(
            648.0,
            385.0,
            image=image_image_2
        )

        image_image_3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        image_3 = canvas.create_image(
            1012.0,
            30.0,
            image=image_image_3
        )

        image_image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = canvas.create_image(
            971.0,
            30.0,
            image=image_image_4
        )

        image_image_5 = PhotoImage(
            file=relative_to_assets("image_5.png"))
        image_5 = canvas.create_image(
            328.0,
            30.0,
            image=image_image_5
        )

        image_image_6 = PhotoImage(
            file=relative_to_assets("image_6.png"))
        image_6 = canvas.create_image(
            534.0,
            30.0,
            image=image_image_6
        )

        image_image_7 = PhotoImage(
            file=relative_to_assets("image_7.png"))
        image_7 = canvas.create_image(
            534.0,
            30.0,
            image=image_image_7
        )

        image_image_8 = PhotoImage(
            file=relative_to_assets("image_8.png"))
        image_8 = canvas.create_image(
            328.0,
            30.0,
            image=image_image_8
        )

        canvas.create_text(
            536.0,
            703.0,
            anchor="nw",
            text="placeholder for dji",
            fill="#64748B",
            font=("ArialMT", 12 * -1)
        )

        canvas.create_text(
            273.0,
            704.0,
            anchor="nw",
            text="placeholder for spx",
            fill="#64748B",
            font=("ArialMT", 12 * -1)
        )

        canvas.create_text(
            404.0,
            704.0,
            anchor="nw",
            text="placeholder for ndx",
            fill="#64748B",
            font=("ArialMT", 12 * -1)
        )

        canvas.create_text(
            405.0,
            176.0,
            anchor="nw",
            text="running",
            fill="#64748B",
            font=("ArialMT", 16 * -1)
        )

        canvas.create_text(
            405.0,
            135.0,
            anchor="nw",
            text="strategy01",
            fill="#64748B",
            font=("ArialMT", 16 * -1)
        )

        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            840.0,
            547.0,
            image=entry_image_1
        )
        entry_1 = Text(
            bd=0,
            bg="#EFF4FB",
            fg="#000716",
            highlightthickness=0
        )
        entry_1.place(
            x=669.0,
            y=472.0,
            width=342.0,
            height=148.0
        )

        entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        entry_bg_2 = canvas.create_image(
            840.0,
            314.0,
            image=entry_image_2
        )
        entry_2 = Text(
            bd=0,
            bg="#EFF4FB",
            fg="#000716",
            highlightthickness=0
        )
        entry_2.place(
            x=669.0,
            y=204.0,
            width=342.0,
            height=218.0
        )

        entry_image_3 = PhotoImage(
            file=relative_to_assets("entry_3.png"))
        entry_bg_3 = canvas.create_image(
            445.0,
            364.0,
            image=entry_image_3
        )
        entry_3 = Text(
            bd=0,
            bg="#EFF4FB",
            fg="#000716",
            highlightthickness=0
        )
        entry_3.place(
            x=274.0,
            y=304.0,
            width=342.0,
            height=118.0
        )

        entry_image_4 = PhotoImage(
            file=relative_to_assets("entry_4.png"))
        entry_bg_4 = canvas.create_image(
            485.0,
            473.5,
            image=entry_image_4
        )
        entry_4 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_4.place(
            x=409.0,
            y=461.0,
            width=152.0,
            height=23.0
        )

        entry_image_5 = PhotoImage(
            file=relative_to_assets("entry_5.png"))
        entry_bg_5 = canvas.create_image(
            485.0,
            509.5,
            image=entry_image_5
        )
        entry_5 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_5.place(
            x=409.0,
            y=497.0,
            width=152.0,
            height=23.0
        )
        # window.resizable(False, False)
        # window.mainloop()
